# .github/ISSUE_TEMPLATE/test.yml
name: Create a new short link
description: Please fill out the form to create a new short link. Do not change the issue title.
title: "Create short link"
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following form to create a short link.
  - type: input
    id: url
    attributes:
      label: URL
      description: Enter the URL you want to shorten.
      placeholder: https://example.com
    validations:
      required: true
  - type: input
    id: slug
    attributes:
      label: Slug
      description: Enter the custom slug for your short link.
      placeholder: mylink
    validations:
      required: false
  - type: input
    id: expiration_date
    attributes:
      label: Expiration Date
      description: Enter the expiration date for the short link in the format YYYY-MM-DD.
      placeholder: 2025-12-31
    validations:
      required: true
